In [1]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)  # Prints the data type of the array

int32


In [2]:
# 2. Given a NumPy array 'arr', check if its data type is float64.


arr = np.array([0.1, 2.5, 3.4], dtype=np.float64)
if arr.dtype == np.float64:
    print("Data type is float64")
else:
    print("Data type is not float64")

Data type is float64


In [3]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.


arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [4]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.


arr = np.array([1, 2, 3, 4])
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[1. 2. 3. 4.]


In [5]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


arr = np.array([0.123456789], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[0.12345679]


In [6]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.


def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1, 2, 3])
print(array_attributes(arr))

((3,), 3, dtype('int32'))


In [7]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dimension(arr))

2


In [8]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.


def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3])
print(item_size_info(arr))

(4, 12)


In [9]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.


def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_strides(arr))

(12, 4)


In [10]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.


def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(shape_stride_relationship(arr))

((2, 3), (12, 4))


In [11]:
# 11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.


def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [12]:
# 12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.


def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# 13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.


def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(0, 10, 2))

[0 2 4 6 8]


In [14]:
# 14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive).

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [15]:
# 15. Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size n x n using numpy.eye.


def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.


def list_to_numpy(arr):
    return np.array(arr)

print(list_to_numpy([1, 2, 3, 4, 5]))

[1 2 3 4 5]


In [17]:
# 17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.


arr = np.array([1, 2, 3])
arr_view = arr.view()
print(arr_view)

[1 2 3]


In [18]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.


def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(concatenate_arrays(arr1, arr2))

[1 2 3 4 5 6]


In [19]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
print(np.concatenate((arr1, arr2.T), axis=1))

[[1 2 5]
 [3 4 6]]


In [20]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.


def stack_arrays(arrays_list):
    return np.vstack(arrays_list)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(stack_arrays([arr1, arr2]))


[[1 2 3]
 [4 5 6]]


In [21]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.


def create_range_array(start, stop, step):
    return np.arange(start, stop+1, step)

print(create_range_array(1, 10, 2))


[1 3 5 7 9]


In [22]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).


def generate_equal_space():
    return np.linspace(0, 1, 10)

print(generate_equal_space())


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


def generate_log_space():
    return np.logspace(0, 3, 5)  # logspace from 10^0 to 10^3, which is 1 to 1000

print(generate_log_space())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import pandas as pd

arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=['Column1', 'Column2', 'Column3'])
df


Column1  Column2  Column3
0       54       97       39
1       14       71       68
2       84       83       73
3       54       92       79
4       35       11       34

In [25]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.


def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {'A': [10, -5, 15], 'B': [-20, 30, -40]}
df = pd.DataFrame(data)
print(replace_negatives_with_zero(df, 'A'))


    A   B
0  10 -20
1   0  30
2  15 -40


In [26]:
# 26. Access the 3rd element from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5])
print(arr[2])

3


In [27]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])

6


In [28]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[arr > 5])

[ 8 10  7]


In [29]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
print(arr[2:6])


[30 40 50]


In [30]:
# 30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [31]:
# 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

def extract_elements(arr, indices):
    return arr[indices]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [2, 2]])
print(extract_elements(arr_2d, indices))

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]


In [32]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_elements(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 5, 8, 12, 15])
print(filter_elements(arr, 8))

[12 15]


In [33]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

def extract_3d_elements(arr, x, y, z):
    return arr[x, y, z]

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
x_indices = np.array([0, 1])
y_indices = np.array([0, 1])
z_indices = np.array([1, 0])
print(extract_3d_elements(arr_3d, x_indices, y_indices, z_indices))

[2 7]


In [34]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def extract_elements_with_conditions(arr):
    return arr[(arr > 3) & (arr < 10)]

arr = np.array([1, 3, 6, 10, 15])
print(extract_elements_with_conditions(arr))

[6]


In [35]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def extract_elements_2d(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])
print(extract_elements_2d(arr_2d, row_indices, col_indices))


[2 9]


In [36]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr += 5
print(arr)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
result = arr2 * arr1.T
print(result)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [38]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
result = arr2 + arr1.T
print(result)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [39]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[10, 20, 30]])
result = arr1 + arr2
print(result)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [40]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2], [3, 4]])
try:
    result = arr1 * arr2  # This will raise a ValueError
except ValueError as e:
    print("Shape mismatch:", e)

Shape mismatch: operands could not be broadcast together with shapes (2,3) (2,2) 


In [41]:
# 41. Calculate column-wise mean for the given array.

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)


[2.5 3.5 4.5]


In [42]:
# 42. Find the maximum value in each row of the given array.

arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(row_max)

[3 6]


In [43]:
# 43. For the given array, find indices of the maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)
print(max_indices)

[1 1 1]


In [44]:
# 44. For the given array, apply a custom function to calculate the moving sum along rows.

def moving_sum(arr, window):
    return np.convolve(arr, np.ones(window), 'valid')

arr = np.array([1, 2, 3, 4, 5])
print(moving_sum(arr, 3))

[ 6.  9. 12.]


In [45]:
# 44. For the given array, apply a custom function to calculate the moving sum along rows.

def moving_sum(arr, window):
    return np.convolve(arr, np.ones(window), 'valid')

arr = np.array([1, 2, 3, 4, 5])
print(moving_sum(arr, 3))

[ 6.  9. 12.]


In [46]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

def reshape_matrix(arr, m, n):
    return arr.reshape(m, n)

arr = np.array([1, 2, 3, 4, 5, 6])
print(reshape_matrix(arr, 2, 3))

[[1 2 3]
 [4 5 6]]


In [47]:
# 47. Create a function that takes a matrix as input and returns the flattened array.

def flatten_matrix(matrix):
    return matrix.flatten()

matrix = np.array([[1, 2], [3, 4]])
print(flatten_matrix(matrix))

[1 2 3 4]


In [48]:
# 48. Write a function that concatenates two given arrays along a specified axis.

def concatenate_along_axis(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_along_axis(arr1, arr2, axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

def split_array(arr, indices_or_sections, axis=0):
    return np.split(arr, indices_or_sections, axis=axis)

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(split_array(arr, 2, axis=0))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [50]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

def insert_and_delete(arr, insert_idx, insert_val, delete_idx):
    arr = np.insert(arr, insert_idx, insert_val)
    arr = np.delete(arr, delete_idx)
    return arr

arr = np.array([1, 2, 3, 4, 5])
print(insert_and_delete(arr, 2, 10, 3))

[ 1  2 10  4  5]


In [51]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(1, 11, size=10)
arr2 = np.arange(1, 11)
result = arr1 + arr2
print(result)

[11 12 13 14 15 14 17  9 18 11]


In [52]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print(result)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [53]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1, 6, size=5)
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1 * arr2
print(result)

[ 4  2 15 20 10]


In [54]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2, 11, 2)
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1 / arr2
print(result)

[2. 2. 2. 2. 2.]


In [55]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
result = arr1 ** arr2
print(result)

[ 1 16 27 16  5]


In [56]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

def count_substring(arr, substring):
    return np.char.count(arr, substring)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print(count_substring(arr, 'hello'))

[1 0 1 0 1]


In [57]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.

def extract_uppercase(arr):
    return np.char.upper(arr)

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print(extract_uppercase(arr))

['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [58]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(['hello', 'world', 'hello', 'numpy'])
print(replace_substring(arr, 'hello', 'hi'))

['hi' 'world' 'hi' 'numpy']


In [59]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'Open'])
arr2 = np.array([' World', ' AI'])
print(concatenate_strings(arr1, arr2))


['Hello World' 'Open AI']


In [60]:
# 60. Write a function that finds the length of the longest string in a NumPy array.

def find_longest_string(arr):
    return np.vectorize(len)(arr).max()

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(find_longest_string(arr))


9


In [61]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

arr = np.random.randint(1, 1001, size=100)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std_dev = np.std(arr)
print(f"Mean: {mean}, Median: {median}, Variance: {variance}, Standard Deviation: {std_dev}")


Mean: 468.87, Median: 447.5, Variance: 102368.33309999999, Standard Deviation: 319.95051664280834


In [62]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

arr = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(arr, 25)
percentile_75 = np.percentile(arr, 75)
print(f"25th Percentile: {percentile_25}, 75th Percentile: {percentile_75}")


25th Percentile: 31.75, 75th Percentile: 71.5


In [63]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

arr1 = np.random.randint(1, 100, size=10)
arr2 = np.random.randint(1, 100, size=10)
correlation_coefficient = np.corrcoef(arr1, arr2)
print(correlation_coefficient)


[[1.         0.63297816]
 [0.63297816 1.        ]]


In [64]:
# 64. Create two matrices and perform matrix multiplication using NumPy's dot function.

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_multiplication = np.dot(matrix1, matrix2)
print(matrix_multiplication)


[[19 22]
 [43 50]]


In [65]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

arr = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)  # Median
percentile_90 = np.percentile(arr, 90)
quartile_1 = np.percentile(arr, 25)
quartile_3 = np.percentile(arr, 75)
print(f"10th Percentile: {percentile_10}, Median: {percentile_50}, 90th Percentile: {percentile_90}, Q1: {quartile_1}, Q3: {quartile_3}")


10th Percentile: 80.7, Median: 411.0, 90th Percentile: 916.5, Q1: 223.0, Q3: 642.5


In [66]:
# 66. Create a NumPy array of integers and find the index of a specific element.

arr = np.array([10, 20, 30, 40, 50])
index_of_element = np.where(arr == 30)[0][0]
print(index_of_element)


2


In [67]:
# 67. Generate a random NumPy array and sort it in ascending order.

arr = np.random.randint(1, 101, size=10)
sorted_arr = np.sort(arr)
print(sorted_arr)


[ 1 12 31 33 41 44 70 76 91 91]


In [68]:
# 68. Filter elements greater than 20 in the given NumPy array.

arr = np.array([10, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
print(filtered_arr)


[25 42 30]


In [69]:
# 69. Filter elements that are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])
divisible_by_3 = arr[arr % 3 == 0]
print(divisible_by_3)


[12 15]


In [70]:
# 70. Filter elements that are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 25, 6, 42, 8, 30])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print(filtered_arr)


[25 30]


In [71]:
# 71. For the given NumPy array, check its byte order using the dtype attribute byteorder.

arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder
print(byte_order)

=


In [72]:
# 72. For the given NumPy array, perform byte swapping in place using byteswap().

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)
print(arr)


[16777216 33554432 50331648]


In [73]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().

arr = np.array([1, 2, 3], dtype=np.int32)
new_byte_order = arr.newbyteorder()
print(new_byte_order)


[16777216 33554432 50331648]


In [74]:
# 74. For the given NumPy array, swap its byte order conditionally based on system endianness using newbyteorder().

arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '>':  # Big-endian
    swapped = arr.newbyteorder('<')  # Swap to little-endian
else:
    swapped = arr.newbyteorder('>')
print(swapped)


[16777216 33554432 50331648]


In [75]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using dtype attribute byteorder.

arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':
    print("Byte swapping not necessary")
else:
    print("Byte swapping might be necessary")


Byte swapping not necessary


In [76]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.random.randint(1, 100, size=(3, 3))
view_slice = matrix[0:2, 0:2]
view_slice[0, 0] = 999
print(matrix)


[[999  19  26]
 [  6  60  12]
 [ 23  93  42]]


In [77]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:3, :]
view_b += 5
print(array_a)


[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]


In [78]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 999
print(orig_array)


[[999   2   3   4]
 [  5   6   7   8]]


In [79]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers.  Extract a copy `data_copy` of elements greater than 5.  Modify an element in `data_copy` and verify if it affects the original `data`.


data = np.random.randint(1, 10, size=(3, 4))  # Create random integer array
data_copy = data[data > 5].copy()  # Extract elements greater than 5 and make a copy

# Modify an element in data_copy
data_copy[0] = 99

# Print results to verify if modification affects original array
print("Original array:\n", data)
print("Modified copy:\n", data_copy)


Original array:
 [[7 4 5 3]
 [7 4 2 1]
 [6 3 2 4]]
Modified copy:
 [99  7  6]


In [80]:
# 81. Create two matrices A and B of identical shape containing integers  and perform addition and subtraction operations between them.

A = np.random.randint(1, 10, size=(3, 3))  # Random 3x3 matrix
B = np.random.randint(1, 10, size=(3, 3))  # Random 3x3 matrix

# Perform addition and subtraction
addition = A + B
subtraction = A - B

# Print results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)


Matrix A:
 [[4 4 3]
 [6 8 9]
 [2 8 9]]
Matrix B:
 [[3 8 4]
 [4 7 4]
 [7 2 5]]
Addition:
 [[ 7 12  7]
 [10 15 13]
 [ 9 10 14]]
Subtraction:
 [[ 1 -4 -1]
 [ 2  1  5]
 [-5  6  4]]


In [81]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.random.randint(1, 10, size=(3, 2))  # 3x2 matrix
D = np.random.randint(1, 10, size=(2, 4))  # 2x4 matrix

# Perform matrix multiplication
multiplication = np.dot(C, D)

# Print results
print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Matrix Multiplication (C * D):\n", multiplication)


Matrix C:
 [[7 3]
 [3 9]
 [9 6]]
Matrix D:
 [[4 6 6 4]
 [4 1 8 1]]
Matrix Multiplication (C * D):
 [[ 40  45  66  31]
 [ 48  27  90  21]
 [ 60  60 102  42]]


In [82]:
# 83. Create a matrix `E` and find its transpose.

E = np.random.randint(1, 10, size=(3, 3))  # 3x3 matrix

# Find the transpose
transpose = E.T

# Print results
print("Matrix E:\n", E)
print("Transpose of E:\n", transpose)


Matrix E:
 [[7 3 6]
 [4 8 2]
 [2 3 8]]
Transpose of E:
 [[7 4 2]
 [3 8 3]
 [6 2 8]]


In [83]:
# 84. Generate a square matrix `F` and compute its determinant.

F = np.random.randint(1, 10, size=(3, 3))  # 3x3 matrix

# Compute determinant
determinant = np.linalg.det(F)

# Print results
print("Matrix F:\n", F)
print("Determinant of F:\n", determinant)


Matrix F:
 [[2 4 8]
 [3 2 6]
 [6 2 2]]
Determinant of F:
 56.00000000000002


In [84]:
# 85. Create a square matrix `G` and find its inverse.

G = np.random.randint(1, 10, size=(3, 3))  # 3x3 matrix

# Find inverse
inverse = np.linalg.inv(G)

# Print results
print("Matrix G:\n", G)
print("Inverse of G:\n", inverse)


Matrix G:
 [[5 3 6]
 [3 7 4]
 [3 1 2]]
Inverse of G:
 [[-0.25  0.    0.75]
 [-0.15  0.2   0.05]
 [ 0.45 -0.1  -0.65]]
